<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ns_snow"
 *
 * Auto generated by Extension Builder 2018-12-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'NS Snow',
    'description' => 'Add nice looking animation effect of falling snow to your TYPO3 site and enjoy winter as well as Christmas.',
    'category' => 'plugin',
    'author' => 'Sanjay Chuahan [NITSAN Technologies]',
    'author_email' => 'sanjay@nitsan.in',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '6.2.0-9.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
