services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Nitsan\NsSnow\:
    resource: '../Classes/*'
    public: true 
  
  Nitsan\NsSnow\Controller\NSnowsController:
    arguments:
      $pageRenderer: '@TYPO3\CMS\Core\Page\PageRenderer'
